//! M8 C-oracle golden comparisons: fill_struct_of_state (rad subset),
//! the pp-level opacity entry points (calc_kappa / calc_kappaes /
//! calc_chi), and the thermal four-force calc_Gi with Comptonization.
//!
//! The PUFFY build (PROBLEM 147) supplies the physics: BREMSSTRAHLUNG +
//! SYNCHROTRON with the Terelfactor suppression, PUFFY kappaes with
//! Klein–Nishina, COMPTONIZATION, MASS=10, HFRAC=1. Matched here by
//! radforce.Params.puffy(). Generated by oracle/harness_opac.c.
//!
//! Tolerances: temperature/ne/Ehat algebra 1e-13; opacity fits 1e-12
//! (pow/cbrt/exp chains — Zig's std.math.pow is not Apple libm's pow);
//! Gi rows 1e-12 normalized by the force scale (terms cancel at LTE).

const std = @import("std");
const config = @import("config.zig");
const layout = @import("layout.zig");
const radforce = @import("physics/radforce.zig");
const gold = @import("testing/golden.zig");

const readGolden = gold.readGolden;
const DevTracker = gold.DevTracker;
const geomFromRecord = gold.geomFromRecord;

const cfg = config.puffy;
const L = layout.VarLayout(cfg);
const NV = L.count;
const gam: f64 = 5.0 / 3.0;

fn ppFromRecord(vals: []const f64) [NV]f64 {
    var pp: [NV]f64 = undefined;
    for (0..NV) |iv| pp[iv] = vals[iv];
    return pp;
}

test "golden: fill_struct_of_state (rad subset) vs C" {
    var g = try readGolden(std.testing.allocator, "rad/rad_thermo.kgld", 36, 13);
    defer g.deinit();
    const p = radforce.Params.puffy();

    var t_therm = DevTracker{};
    var t_opac = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        const pp = ppFromRecord(r.in[23..36]);

        const st = try radforce.fillRadState(cfg, pp, &geo, gam, &p);

        t_therm.add(r.out[0], st.tgas, ir);
        t_therm.add(r.out[1], st.te, ir);
        t_therm.add(r.out[2], st.ne, ir);
        t_therm.add(r.out[3], st.ehat, ir);
        t_therm.add(r.out[4], st.tradbb, ir);
        t_therm.add(r.out[5], st.kappaes, ir);

        // opacities normalized per record by the largest channel — the
        // Rosseland/number fields span many orders of magnitude
        var scale: f64 = 1e-300;
        for (6..13) |k| scale = @max(scale, @abs(r.out[k]));
        t_opac.add(r.out[6] / scale, st.opac.gas_abs / scale, ir);
        t_opac.add(r.out[7] / scale, st.opac.rad_abs / scale, ir);
        t_opac.add(r.out[8] / scale, st.opac.gas_num / scale, ir);
        t_opac.add(r.out[9] / scale, st.opac.rad_num / scale, ir);
        t_opac.add(r.out[10] / scale, st.opac.gas_ross / scale, ir);
        t_opac.add(r.out[11] / scale, st.opac.rad_ross / scale, ir);
        t_opac.add(r.out[12] / scale, st.kappa / scale, ir);
    }
    try t_therm.check(1e-13, "state thermo (Tgas/Te/ne/Ehat/TradBB/kappaes)");
    try t_opac.check(1e-12, "state opacities (record-scale normalized)");
}

test "golden: calc_kappa / calc_kappaes / calc_chi vs C" {
    var g = try readGolden(std.testing.allocator, "rad/rad_opac.kgld", 36, 3);
    defer g.deinit();
    const p = radforce.Params.puffy();

    var t = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        const pp = ppFromRecord(r.in[23..36]);

        const kappa = try radforce.calcKappa(cfg, pp, &geo, gam, &p);
        const kappaes = radforce.calcKappaes(cfg, pp, gam, &p);
        const chi = try radforce.calcChi(cfg, pp, &geo, gam, &p);

        t.add(r.out[0], kappa, ir);
        t.add(r.out[1], kappaes, ir);
        t.add(r.out[2], chi, ir);
    }
    try t.check(1e-12, "calc_kappa/kappaes/chi");
}

test "golden: calc_Gi (thermal four-force + Comptonization) vs C" {
    var g = try readGolden(std.testing.allocator, "rad/rad_gi.kgld", 36, 8);
    defer g.deinit();
    const p = radforce.Params.puffy();

    var t = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        const pp = ppFromRecord(r.in[23..36]);

        const st = try radforce.fillRadState(cfg, pp, &geo, gam, &p);
        const gi = try radforce.calcGiFromState(&st, .{
            pp[L.index(.vx)], pp[L.index(.vy)], pp[L.index(.vz)],
        }, &geo, &p);

        // normalize by the four-force scale: the flux, emission and
        // Compton terms individually (they cancel near LTE). The Compton
        // factor (Trad − Te) is a cancellation whose inputs both sides
        // only agree on to ~ulp(Te) — its sensitivity |∂coeff/∂Trad|·Te
        // belongs in the scale (dominant at θe ≫ 1 where the bracket
        // amplifies): evaluate the coefficient with Trad − Te := Te.
        const c = &p.c;
        const b = c.sigma_rad_over_pi * st.te * st.te * st.te * st.te;
        var st_sens = st;
        st_sens.trad = 2.0 * st.te;
        const scale = (st.opac.rad_ross + st.kappaes) * st.ehat +
            st.opac.gas_abs * c.fourpi * b +
            @abs(radforce.comptComptonCoeff(c, &st_sens));

        for (0..4) |i| {
            t.add(r.out[i] / scale, gi.lab[i] / scale, ir);
            t.add(r.out[4 + i] / scale, gi.ff[i] / scale, ir);
        }
    }
    try t.check(1e-12, "calc_Gi lab/ff (force-scale normalized)");
}
