//! M7 C-oracle golden comparisons: calc_Rij_M1 / calc_ff_Rtt, the
//! closed-form u2p_rad inversion (branch decisions exact, primitives at
//! 1e-12), the τ-limited radiative wavespeeds, and check_floors_rad.
//!
//! Records carry C's own geometry (see golden_state_test.zig) so these
//! are pure state-algebra comparisons — the PUFFY build supplies
//! GAMMAMAXRAD=10 and the PUFFY EE ratio floors, matched here by
//! RadParams.puffy. Generated by oracle/harness_rad.c.

const std = @import("std");
const config = @import("config.zig");
const layout = @import("layout.zig");
const relele = @import("relele.zig");
const radiation = @import("physics/radiation.zig");
const invert_rad = @import("solve/invert_rad.zig");
const gold = @import("testing/golden.zig");

const readGolden = gold.readGolden;
const DevTracker = gold.DevTracker;
const geomFromRecord = gold.geomFromRecord;

const cfg = config.puffy;
const L = layout.VarLayout(cfg);
const NV = L.count;
const rp = invert_rad.RadParams.puffy;

test "golden: calc_Rij_M1 + calc_ff_Rtt vs C" {
    var g = try readGolden(std.testing.allocator, "rad/rad_rij.kgld", 33, 21);
    defer g.deinit();

    var t_rij = DevTracker{};
    var t_rtt = DevTracker{};
    var t_u = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..20], .mks2, @splat(0));
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[20 + iv];

        const rij = try radiation.calcRij(cfg, pp, &geo);
        var n: usize = 0;
        // normalize by the record's largest component — rows pass through 0
        var scale: f64 = 1e-300;
        for (0..16) |k| scale = @max(scale, @abs(r.out[k]));
        for (0..4) |i| {
            for (0..4) |j| {
                t_rij.add(r.out[n] / scale, rij[i][j] / scale, ir);
                n += 1;
            }
        }

        const ff = try radiation.calcFfRtt(cfg, pp, &geo);
        t_rtt.add(r.out[16] / scale, ff.rtt / scale, ir);
        for (0..4) |i| t_u.add(r.out[17 + i], ff.ucon[i], ir);
    }
    try t_rij.check(1e-14, "calc_Rij_M1 (record-scale normalized)");
    try t_rtt.check(1e-13, "calc_ff_Rtt");
    try t_u.check(1e-14, "ff ucon");
}

test "golden: u2p_rad closed-form inversion vs C (branches exact)" {
    var g = try readGolden(std.testing.allocator, "rad/rad_u2prad.kgld", 31, 6);
    defer g.deinit();

    var t = DevTracker{};
    var n_cold: usize = 0;
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        var uu: [NV]f64 = @splat(0);
        uu[L.index(.ee)] = r.in[23];
        uu[L.index(.fx)] = r.in[24];
        uu[L.index(.fy)] = r.in[25];
        uu[L.index(.fz)] = r.in[26];

        var pp: [NV]f64 = @splat(0);
        pp[L.index(.ee)] = r.in[27];
        pp[L.index(.fx)] = r.in[28];
        pp[L.index(.fy)] = r.in[29];
        pp[L.index(.fz)] = r.in[30];

        const res = invert_rad.u2pRad(cfg, uu, &pp, &geo, rp);

        // branch decisions must match exactly
        try std.testing.expectEqual(@as(i32, @intFromFloat(r.out[0])), res.ret);
        try std.testing.expectEqual(@as(i32, @intFromFloat(r.out[1])), @as(i32, @intFromBool(res.corrected)));
        if (res.corrected) n_cold += 1;

        // primitives (pass-through values included when ret == -1); the
        // flux rows are normalized by Ê's scale — they pass through zero
        const scale = @max(@abs(r.out[2]), 1e-300);
        t.add(r.out[2] / scale, pp[L.index(.ee)] / scale, ir);
        t.add(r.out[3], pp[L.index(.fx)], ir);
        t.add(r.out[4], pp[L.index(.fy)], ir);
        t.add(r.out[5], pp[L.index(.fz)], ir);
    }
    std.debug.print("u2p_rad golden: {d}/{d} records took a cold branch\n", .{ n_cold, g.nrec });
    try t.check(1e-12, "u2p_rad primitives");
}

test "golden: calc_rad_wavespeeds (tau limiter) vs C" {
    var g = try readGolden(std.testing.allocator, "rad/rad_wavespeeds.kgld", 36, 8);
    defer g.deinit();

    // PUFFY C build: TNX,TNY > 1, TNZ == 1 (z slots untouched, not recorded)
    const dims = [3]bool{ true, true, false };

    var t = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..20], .mks2, @splat(0));
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[20 + iv];
        const tautot = [3]f64{ r.in[33], r.in[34], r.in[35] };

        const aval = try radiation.calcRadWavespeeds(cfg, pp, &geo, tautot, dims);
        t.add(r.out[0], aval[0], ir);
        t.add(r.out[1], aval[1], ir);
        t.add(r.out[2], aval[2], ir);
        t.add(r.out[3], aval[3], ir);
        t.add(r.out[4], aval[6], ir);
        t.add(r.out[5], aval[7], ir);
        t.add(r.out[6], aval[8], ir);
        t.add(r.out[7], aval[9], ir);
    }
    try t.check(1e-12, "calc_rad_wavespeeds");
}

test "golden: check_floors_rad vs C" {
    var g = try readGolden(std.testing.allocator, "rad/rad_floors.kgld", 36, 14);
    defer g.deinit();

    var t = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[23 + iv];

        const ret = try invert_rad.checkFloorsRad(cfg, &pp, &geo, rp);

        try std.testing.expectEqual(@as(i32, @intFromFloat(r.out[0])), ret);
        for (0..NV) |iv| {
            const scale = @max(@abs(r.out[1 + iv]), 1e-300);
            t.add(r.out[1 + iv] / scale, pp[iv] / scale, ir);
        }
    }
    try t.check(1e-13, "check_floors_rad");
}
