//! C-oracle golden comparisons (M2/M3: relele, frames, p2u, u2p, floors).
//!
//! Every record carries C's *own* geometry (gg, GG, gdet, alpha, gttpert),
//! so these tests compare pure state algebra — the MKS2 two-π metric spread
//! never enters, and gates stay at 1e-13 for closed-form code and 1e-8 for
//! the iterative inversion (both sides stop at U2PCONV = 1e-10).
//!
//! Symmetric 4×4 blocks are stored as 10 upper-triangle values in the order
//! (00,01,02,03,11,12,13,22,23,33). Generated by oracle/harness_state.c.

const std = @import("std");
const build_options = @import("build_options");
const config = @import("config.zig");
const layout = @import("layout.zig");
const relele = @import("relele.zig");
const frames = @import("frames.zig");
const mhd = @import("physics/bfield.zig");
const hydro = @import("physics/hydro.zig");
const p2u_mod = @import("p2u.zig");
const invert = @import("solve/invert.zig");
const metric = @import("metric/metric.zig");
const Geometry = @import("geometry.zig").Geometry;
const gold = @import("testing/golden.zig");

const readGolden = gold.readGolden;
const DevTracker = gold.DevTracker;
const geomFromRecord = gold.geomFromRecord;
const coordsFromId = gold.coordsFromId;

const puffy_mp = metric.MetricParams{ .a = 0.0, .mksr0 = 0.1, .mksh0 = 0.9 };
const pgamma: f64 = 5.0 / 3.0;

const cfg = config.puffy;
const L = layout.VarLayout(cfg);
const NV = L.count;

//
// ---- the tests -------------------------------------------------------------
//

test "golden: conv_vels all 9 pairs vs C" {
    var g = try readGolden(std.testing.allocator, "state/relele_convvels.kgld", 25, 4);
    defer g.deinit();

    var t = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..20], .ks, @splat(0));
        const w1: relele.VelType = @enumFromInt(@as(u8, @intFromFloat(r.in[20])));
        const w2: relele.VelType = @enumFromInt(@as(u8, @intFromFloat(r.in[21])));
        const uin = [4]f64{ 0, r.in[22], r.in[23], r.in[24] };
        const uout = try relele.convert(uin, w1, w2, &geo, .recompute_ut);
        for (0..4) |i| t.add(r.out[i], uout[i], ir);
    }
    try t.check(1e-13, "conv_vels");
}

test "golden: Lorentz matrix and vector boosts vs C" {
    var g = try readGolden(std.testing.allocator, "state/relele_boost.kgld", 27, 24);
    defer g.deinit();

    var t_l = DevTracker{};
    var t_b = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..20], .ks, @splat(0));
        const vel = [3]f64{ r.in[20], r.in[21], r.in[22] };
        const a = [4]f64{ r.in[23], r.in[24], r.in[25], r.in[26] };

        const l = try frames.lorentzLab2Ff(vel, &geo);
        var n: usize = 0;
        for (0..4) |i| {
            for (0..4) |j| {
                t_l.add(r.out[n], l[i][j], ir);
                n += 1;
            }
        }
        const b1 = try frames.boost2Lab2Ff(a, vel, &geo);
        for (0..4) |i| {
            t_b.add(r.out[n], b1[i], ir);
            n += 1;
        }
        const b2 = try frames.boost2Ff2Lab(a, vel, &geo);
        for (0..4) |i| {
            t_b.add(r.out[n], b2[i], ir);
            n += 1;
        }
    }
    try t_l.check(1e-13, "Lorentz lab2ff");
    try t_b.check(1e-13, "boost2 lab2ff/ff2lab");
}

test "golden: trans_pall_coco vs C (MKS2 ↔ KS/BL)" {
    var g = try readGolden(std.testing.allocator, "state/frames_transpall.kgld", 58, 13);
    defer g.deinit();

    var t = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const co1 = try coordsFromId(r.in[0]);
        const co2 = try coordsFromId(r.in[1]);
        const x = [4]f64{ 0, r.in[2], r.in[3], r.in[4] };
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[5 + iv];
        const g1 = geomFromRecord(r.in[18..38], co1, x);
        const g2 = geomFromRecord(r.in[38..58], co2, @splat(0));

        const pp2 = try frames.transPallCoco(cfg, pp, &g1, &g2, puffy_mp);
        for (0..NV) |iv| t.add(r.out[iv], pp2[iv], ir);
    }
    try t.check(1e-10, "trans_pall_coco");
}

test "golden: calc_Tij + four-vectors vs C" {
    var g = try readGolden(std.testing.allocator, "state/physics_tij.kgld", 33, 33);
    defer g.deinit();

    var t_tij = DevTracker{};
    var t_u = DevTracker{};
    var t_b = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..20], .ks, @splat(0));
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[20 + iv];

        const tij = try hydro.calcTij(cfg, pp, &geo, pgamma);
        const u = try relele.uconUcovFromPrims(.{ pp[2], pp[3], pp[4] }, &geo);
        const b = mhd.bconBcovBsqFrom4vel(.{ pp[6], pp[7], pp[8] }, u.con, u.cov, &geo);

        var n: usize = 0;
        for (0..4) |i| {
            for (0..4) |j| {
                t_tij.add(r.out[n], tij[i][j], ir);
                n += 1;
            }
        }
        for (0..4) |i| {
            t_u.add(r.out[n], u.con[i], ir);
            n += 1;
        }
        for (0..4) |i| {
            t_u.add(r.out[n], u.cov[i], ir);
            n += 1;
        }
        for (0..4) |i| {
            t_b.add(r.out[n], b.bcon[i], ir);
            n += 1;
        }
        for (0..4) |i| {
            t_b.add(r.out[n], b.bcov[i], ir);
            n += 1;
        }
        t_b.add(r.out[n], b.bsq, ir);
    }
    try t_tij.check(1e-13, "calc_Tij");
    try t_u.check(1e-13, "ucon/ucov");
    try t_b.check(1e-13, "bcon/bcov/bsq");
}

test "golden: p2u (mhd + rad) vs C" {
    var g = try readGolden(std.testing.allocator, "state/p2u.kgld", 36, 13);
    defer g.deinit();

    // Momentum rows can be exact zeros (at-rest states) reached through
    // catastrophic cancellation; the roundoff noise there sits at the scale
    // of the record's LARGEST conserved of the same family (gdet·η·u^t·…),
    // and C's clang build contracts FMAs where Zig does not. Normalize each
    // row by its family's max |uu| instead of per-element.
    var t = DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[23 + iv];

        const uu = try p2u_mod.p2u(cfg, pp, &geo, pgamma);

        var scale_mhd: f64 = 1e-300;
        var scale_rad: f64 = 1e-300;
        for (0..9) |iv| scale_mhd = @max(scale_mhd, @abs(r.out[iv]));
        for (9..NV) |iv| scale_rad = @max(scale_rad, @abs(r.out[iv]));
        for (0..NV) |iv| {
            const s = if (iv < 9) scale_mhd else scale_rad;
            t.add(r.out[iv] / s, uu[iv] / s, ir);
        }
    }
    try t.check(1e-13, "p2u (family-scale normalized)");
}

test "golden: u2p_solver_W hot + entropy vs C" {
    var g = try readGolden(std.testing.allocator, "state/u2p_solver.kgld", 49, 20);
    defer g.deinit();

    var t_hot = DevTracker{};
    var t_entr = DevTracker{};
    var code_mismatch: usize = 0;
    var outcome_mismatch: usize = 0;

    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        var uu: [NV]f64 = undefined;
        var guess: [NV]f64 = undefined;
        for (0..NV) |iv| uu[iv] = r.in[23 + iv];
        for (0..NV) |iv| guess[iv] = r.in[36 + iv];

        const c_ret_hot: i32 = @intFromFloat(r.out[0]);
        const c_ret_entr: i32 = @intFromFloat(r.out[10]);

        var pp_hot = guess;
        const ret_hot = invert.u2pSolverW(cfg, uu, &pp_hot, &geo, .hot, pgamma);
        var pp_entr = guess;
        const ret_entr = invert.u2pSolverW(cfg, uu, &pp_entr, &geo, .entropy, pgamma);

        // ok/fail outcome must agree exactly; the specific failure code is
        // reported but not gating (different libm can pick a different rung)
        if ((c_ret_hot == 0) != (ret_hot == 0) or (c_ret_entr == 0) != (ret_entr == 0)) {
            outcome_mismatch += 1;
            std.debug.print("u2p outcome mismatch rec {d}: C ({d},{d}) zig ({d},{d})\n", .{ ir, c_ret_hot, c_ret_entr, ret_hot, ret_entr });
        } else if (c_ret_hot != ret_hot or c_ret_entr != ret_entr) {
            code_mismatch += 1;
        }

        if (c_ret_hot == 0 and ret_hot == 0) {
            for (0..9) |iv| t_hot.add(r.out[1 + iv], pp_hot[iv], ir);
        }
        if (c_ret_entr == 0 and ret_entr == 0) {
            for (0..9) |iv| t_entr.add(r.out[11 + iv], pp_entr[iv], ir);
        }
    }
    std.debug.print("u2p golden: {d} failure-code diffs (non-gating)\n", .{code_mismatch});
    try std.testing.expectEqual(@as(usize, 0), outcome_mismatch);
    try t_hot.check(1e-8, "u2p hot prims");
    try t_entr.check(1e-8, "u2p entropy prims");
}

test "golden: check_floors_mhd vs C" {
    var g = try readGolden(std.testing.allocator, "state/floors.kgld", 36, 14);
    defer g.deinit();

    var t = DevTracker{};
    var ret_mismatch: usize = 0;
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[23 + iv];

        const c_ret: i32 = @intFromFloat(r.out[0]);
        const ret = try invert.checkFloorsMhd(cfg, &pp, &geo, pgamma, .puffy);
        if (ret != c_ret) {
            ret_mismatch += 1;
            std.debug.print("floors ret mismatch rec {d}: C {d} zig {d}\n", .{ ir, c_ret, ret });
        }
        for (0..NV) |iv| t.add(r.out[1 + iv], pp[iv], ir);
    }
    try std.testing.expectEqual(@as(usize, 0), ret_mismatch);
    try t.check(1e-12, "check_floors_mhd");
}
