//! C-oracle golden comparisons (M4: reconstruction, wavespeeds, fluxes).
//! Generated by oracle/harness_flux.c; geometry embedded per record as in
//! golden_state_test.zig.

const std = @import("std");
const config = @import("../../config.zig");
const layout = @import("../../layout.zig");
const recon = @import("../../fv/recon.zig");
const wavespeeds = @import("../../physics/wavespeeds.zig");
const fluxmod = @import("../../physics/flux.zig");
const gold = @import("../../testing/golden.zig");

const cfg = config.puffy;
const L = layout.VarLayout(cfg);
const NV = L.count;
const pgamma: f64 = 5.0 / 3.0;

test "golden: avg2point (donor/minmod-θ/PPM, order reduction) vs C" {
    var g = try gold.readGolden(std.testing.allocator, "flux/recon.kgld", 12, 2);
    defer g.deinit();

    var t = gold.DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const u = [5]f64{ r.in[0], r.in[1], r.in[2], r.in[3], r.in[4] };
        const dx = [5]f64{ r.in[5], r.in[6], r.in[7], r.in[8], r.in[9] };
        const param: u8 = @intFromFloat(r.in[10]);
        const theta = r.in[11];
        // PUFFY: INT_ORDER = 2, reduced by param (the caller-side policy
        // sim.zig applies via base_order -| reduce)
        const scheme: recon.Scheme = switch (@as(u8, 2) -| param) {
            0 => .donor,
            1 => .{ .linear = .{ .theta = theta } },
            else => .ppm,
        };
        const f = recon.reconstruct(f64, scheme, u, dx);
        t.add(r.out[0], f.left, ir);
        t.add(r.out[1], f.right, ir);
    }
    try t.check(1e-14, "avg2point");
}

test "golden: gas wavespeeds (x,y) vs C" {
    var g = try gold.readGolden(std.testing.allocator, "flux/wavespeed.kgld", 36, 4);
    defer g.deinit();

    var t = gold.DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = gold.geomFromRecord(r.in[0..23], .mks2, @splat(0));
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[23 + iv];

        // PUFFY: TNX, TNY > 1, TNZ == 1 (z entries are uninitialized in C)
        const a = try wavespeeds.gasWavespeedsLr(cfg, pp, &geo, pgamma, .{ true, true, false });
        for (0..4) |i| t.add(r.out[i], a[i], ir);
    }
    try t.check(1e-13, "gas wavespeeds l/r");
}

test "golden: f_flux_prime (all 13 rows, Rijvisc = 0) vs C" {
    var g = try gold.readGolden(std.testing.allocator, "flux/fluxprime.kgld", 37, 13);
    defer g.deinit();

    // same per-family scale normalization as the p2u golden: momentum/flux
    // rows that cancel to ~0 carry FMA-difference noise at the family scale
    var t = gold.DevTracker{};
    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = gold.geomFromRecord(r.in[0..23], .mks2, @splat(0));
        const idim: usize = @intFromFloat(r.in[23]);
        var pp: [NV]f64 = undefined;
        for (0..NV) |iv| pp[iv] = r.in[24 + iv];

        const ff = try fluxmod.fFluxPrime(cfg, pp, idim, &geo, pgamma);

        var scale_mhd: f64 = 1e-300;
        var scale_rad: f64 = 1e-300;
        for (0..9) |iv| scale_mhd = @max(scale_mhd, @abs(r.out[iv]));
        for (9..NV) |iv| scale_rad = @max(scale_rad, @abs(r.out[iv]));
        for (0..NV) |iv| {
            const s = if (iv < 9) scale_mhd else scale_rad;
            t.add(r.out[iv] / s, ff[iv] / s, ir);
        }
    }
    try t.check(1e-13, "f_flux_prime (family-scale normalized)");
}
