//! M9 C-oracle golden comparison: solve_implicit_lab — the full implicit
//! rung ladder on PUFFY grid cells over ~10 decades of κΔt stiffness.
//!
//! Both sides stop at RADIMPCONV = 1e-10 residuals but walk different
//! FD-Jacobian/LU floating-point paths, and the residual-to-root
//! conditioning amplifies at τ ≫ 1 — converged primitives gate at 1e-6
//! (the plan's justified bound). Success/failure and the successful
//! rung (whichprim/whicheq/whichframe) are compared exactly, with a
//! small allowance for razor-edge records that converge on different
//! rungs. Generated by oracle/harness_implicit.c.

const std = @import("std");
const config = @import("../../config.zig");
const layout = @import("../../layout.zig");
const radforce = @import("../../physics/radforce.zig");
const invert_rad = @import("../../solve/invert_rad.zig");
const implicit = @import("../../solve/implicit.zig");
const p2u_mod = @import("../../p2u.zig");
const Geometry = @import("../../geometry.zig").Geometry;
const gold = @import("../../testing/golden.zig");

const readGolden = gold.readGolden;
const geomFromRecord = gold.geomFromRecord;

const cfg = config.puffy;
const L = layout.VarLayout(cfg);
const NV = L.count;
const ImplT = implicit.Solver(cfg);
const gam: f64 = 5.0 / 3.0;

/// max normalized residual of a candidate solution against the
/// post-explicit reference, on the given rung (inf on any error)
fn trueResidual(
    pp: *const [NV]f64,
    res: implicit.Result,
    pp00: *const [NV]f64,
    dt: f64,
    geo: *const Geometry,
    p: *const radforce.Params,
) f64 {
    const inf = std.math.inf(f64);
    const uu00 = p2u_mod.p2u(cfg, pp00.*, geo, gam) catch return inf;
    const st00 = radforce.fillRadState(cfg, pp00.*, geo, gam, p) catch return inf;
    const uux = p2u_mod.p2u(cfg, pp.*, geo, gam) catch return inf;
    const stx = radforce.fillRadState(cfg, pp.*, geo, gam, p) catch return inf;
    var fx: [4]f64 = undefined;
    return ImplT.residual(&uux, pp, &stx, &uu00, &st00, dt, geo, p, res.whichprim, res.whicheq, res.whichframe, &fx) catch inf;
}

test "golden: solve_implicit_lab (full rung ladder) vs C" {
    var g = try readGolden(std.testing.allocator, "rad/rad_implicit.kgld", 37, 18);
    defer g.deinit();

    const p = radforce.Params.puffy();
    const rp = invert_rad.RadParams.puffy;
    const ip = implicit.ImplicitParams.puffy;

    var n_ok_c: usize = 0;
    var n_ok_agree: usize = 0;
    var n_rung_agree: usize = 0;
    var n_both_ok: usize = 0;
    var n_compared: usize = 0;
    var iter_diff_max: i64 = 0;
    var worst_pp: f64 = 0;
    var worst_rec: usize = 0;

    for (0..g.nrec) |ir| {
        const r = g.rec(ir);
        const geo = geomFromRecord(r.in[0..23], .mks2, @splat(0));
        const dt = r.in[23];
        var pp0: [NV]f64 = undefined;
        for (0..NV) |iv| pp0[iv] = r.in[24 + iv];

        var pp = pp0;
        var uu: [NV]f64 = undefined;
        const res = ImplT.solveImplicitLab(&uu, &pp, &geo, dt, gam, rp, &p, &ip);

        const c_ok = r.out[0] == 0.0;
        if (c_ok) n_ok_c += 1;
        if (c_ok == res.ok) n_ok_agree += 1;

        if (c_ok and res.ok) {
            n_both_ok += 1;

            const c_prim: i32 = @intFromFloat(r.out[1]);
            const c_eq: i32 = @intFromFloat(r.out[2]);
            const c_frame: i32 = @intFromFloat(r.out[3]);
            const same_rung = c_prim == @intFromEnum(res.whichprim) and
                c_eq == @intFromEnum(res.whicheq) and
                c_frame == @intFromEnum(res.whichframe);
            if (!same_rung) continue;
            n_rung_agree += 1;

            const c_iters: i64 = @intFromFloat(r.out[4]);
            const d = c_iters - @as(i64, @intCast(res.iters));
            iter_diff_max = @max(iter_diff_max, @as(i64, @intCast(@abs(d))));

            // the relative-change exit can accept heavily-damped stalls
            // (in C exactly as here) at different points along the walk —
            // compare only answers that demonstrably satisfy the
            // equations: both sides' residuals < 1e-8
            var c_pp: [NV]f64 = undefined;
            for (0..NV) |iv| c_pp[iv] = r.out[5 + iv];
            const err_z = trueResidual(&pp, res, &pp0, dt, &geo, &p);
            const err_c = trueResidual(&c_pp, res, &pp0, dt, &geo, &p);
            if (!(err_z < 1e-8 and err_c < 1e-8)) continue;
            n_compared += 1;

            // velocity/flux rows normalized by the largest velocity of
            // either side (they pass through zero)
            var vmax: f64 = 1e-14;
            inline for ([_]layout.VarTag{ .vx, .vy, .vz, .fx, .fy, .fz }) |tag| {
                vmax = @max(vmax, @max(@abs(c_pp[L.index(tag)]), @abs(pp[L.index(tag)])));
            }
            for (0..NV) |iv| {
                const is_vel = (iv >= L.index(.vx) and iv <= L.index(.vz)) or
                    (iv >= L.index(.fx) and iv <= L.index(.fz));
                const scale = if (is_vel) vmax else @max(@max(@abs(c_pp[iv]), @abs(pp[iv])), 1e-300);
                const dev = @abs(c_pp[iv] - pp[iv]) / scale;
                if (dev > worst_pp) {
                    worst_pp = dev;
                    worst_rec = ir;
                }
            }
        }
    }

    std.debug.print(
        "implicit golden: C ok {d}/{d}; ok-agreement {d}/{d}; rung agreement {d}/{d}; " ++
            "residual-verified compared {d}; max iter diff {d}; worst pp dev {e:.3} (rec {d})\n",
        .{ n_ok_c, g.nrec, n_ok_agree, g.nrec, n_rung_agree, n_both_ok, n_compared, iter_diff_max, worst_pp, worst_rec },
    );

    // success/failure agreement on ≥ 97% of records (was ≥ 98%: the
    // koral_lite entropy-derivative fix, dwmrho0dW = 1/gamma -> 1/gamma^2,
    // shifts the Newton path enough to move ~8/336 records across the
    // convergence boundary — 328/336 = 97.6% observed); matching rungs on
    // ≥ 90% of joint successes; a healthy residual-verified sample whose
    // primitives agree at 1e-6 (both sides stop at 1e-10 residuals; the
    // residual→root conditioning at τ ≫ 1 justifies the bound)
    try std.testing.expect(n_ok_agree * 100 >= g.nrec * 97);
    try std.testing.expect(n_rung_agree * 10 >= n_both_ok * 9);
    try std.testing.expect(n_compared >= 40);
    try std.testing.expect(worst_pp <= 1e-6);
}
